---
title: "Doing Data Science Portfolio"
author: "Dylan Scott"
date: "3/21/2021"
output: html_document
---
<script type="text/javascript">
    function ShowHideDiv() {
        var studentdisplay = document.getElementById("studentdisplay");
        var dylaninfo = document.getElementById("dylaninfo");
        dylaninfo.style.display = studentdisplay.value == "dylan" ? "block" : "none";
        dvinfo.style.display = studentdisplay.value == "dv" ? "block" : "none";

    }
</script>
<label for="student">Choose Your Character:</label>

</select>
    <select id = "studentdisplay" onchange = "ShowHideDiv()">
        <option value="blank"> </option>
        <option value="dylan">Dylan Scott</option>
        <option value="dv">Darth Vader</option>            
    </select>
<hr />
<div id="dylaninfo" style="display: none">
### Backstory:
Dylan is a student at Southern Methodist University studying a masters in Data Science
<br>He grew up in Detroit and went to Michigan State University for ungrad. <p style="color:green">GO GREEN</p>
<br> I currently work as a CRM Architect in Fort Worth, TX
<br>
<br><b>Hobbies</b>
<ul>
  <li>Rock Climbing</li>
  <li>Live Country Music</li>
  <li>Rodeos</li>
  <li>Weekly Game Nights with Friends</li>
  <li>Cowboy boots and hats</li>

</ul>

<br><b> Feel free to check out my other tabs. They will contain the other projects I have worked on.</br></b>

</div>
<div id="dvinfo" style="display: none">
### Backstory:
Darth Vader is Dylan's cat and partner in typing as he is always on the keyboard when it is time to do homework.
<br>At 15 LBs he is force to be recon with and was recruited to the University of Tennessee to play running back.
<br>
<br><b>His hobbies are:</b>
<ul>
  <li>Napping</li>
  <li>Typing random letters</li>
  <li>Chasing laser pointers</li>
  <li>More Napping</li>
</ul>

</div>
